export { EnrichedTextInput } from './web/EnrichedTextInput';
export { EnrichedText } from './web/EnrichedText';
export type {
  CustomEmoji,
  EnrichedInputStyle,
  EnrichedTextInputProps,
  EnrichedTextProps,
  OnChangeTextEvent,
  OnChangeHtmlEvent,
  OnChangeStateEvent,
  OnLinkDetected,
  OnMentionDetected,
  OnChangeSelectionEvent,
  OnCaretChangeEvent,
  OnKeyPressEvent,
  OnPasteImagesEvent,
  OnPasteEvent,
  OnSubmitEditing,
  HtmlStyle,
  MentionStyleProperties,
  FocusEvent,
  BlurEvent,
  EnrichedTextInputInstance,
  EnrichedTextInstance,
  ContextMenuItem,
  OnChangeMentionEvent,
  EnrichedTextHtmlStyle,
  OnMentionPressEvent,
  OnLinkPressEvent,
  TextShortcut,
} from './types';
